sudo: false
dist: xenial
language: node_js
node_js: lts/*

addons:
  firefox: latest
  chrome: stable

script:

- if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
    yarn test:sauce && yarn test:visual;
  else
    yarn check:version &&
    yarn lint &&
    yarn test;
  fi

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
